const config = require('./config.js')

function higher_pow2(n) {
    const p = Math.ceil(Math.log(n) / Math.log(2))
    return Math.pow(2, p)
}

// The dimensions of the map image in pixels generated by Vips at the highest quality zoom
const map_pixel_width = higher_pow2(config.image_width)
const map_pixel_height = higher_pow2(config.image_height)
// The dimensions of the map in coordinates
const map_width = map_pixel_width/config.tile_width
const map_height = map_pixel_height/config.tile_width
// The size of the most zoomed-out map tile in coordinates
const tile_zoom0_size = Math.max(map_width, map_height)

// The location of the Hopeport Portal Stone in coordinates, relative to the topleft corner of the image
const hopeport_portal_stone_x = Math.floor(config.hopeport_portal_stone_image_x/config.tile_width)
const hopeport_portal_stone_y = Math.floor(config.hopeport_portal_stone_image_y/config.tile_width)
// The borders of the most zoomed-out map tile map in coordinates
const border_left = config.hopeport_portal_stone_coord_x - hopeport_portal_stone_x
const border_up = config.hopeport_portal_stone_coord_y - hopeport_portal_stone_y
const border_right = border_left + map_width
const border_down = border_up + map_height

// Automatically translate the map so that the Hopeport Portal Stone is set to the desired coordinate in the config
// Also flip the y axis
const CRS = L.Util.extend(L.CRS.Simple, {transformation: new L.Transformation(1, -border_left, 1, -border_up)})

module.exports = {
    CRS,
    tile_zoom0_size,
    bounds: L.latLngBounds([border_up, border_left], [border_down, border_right])
}